Add missing docstring for LightningWork.stop()
Lightning-AI/lightning pull request #13368
Opened 2022-06-22 14:18 UTC by rasbt

## What does this PR do?

Adds a docstring for `LightningWork`'s `.stop()`. Right now, the problem is that `stop()` doesn't show up in the API docs (https://lightning.ai/lightning-docs/core_api/lightning_work/lightning_work.html), and adding the docstring should fix this.

### Does your PR introduce any breaking changes? If yes, please list them.

N/A

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/Lightning-AI/lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-06-22 15:26 UTC, awaelchli approved these changes

2022-06-22 16:03 UTC, carmocca requested changes

2022-07-22 10:58 UTC, tchaton approved these changes
LGTM !

2022-07-22 12:57 UTC, manskx approved these changes

2022-07-25 05:14 UTC, hhsecond approved these changes

2022-07-25 14:08 UTC, merged