Restore log step during restart
Lightning-AI/lightning pull request #13467
Opened 2022-06-30 10:27 UTC by rohitgr7

## What does this PR do?

Fixes #12274

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-06-30 11:05 UTC, carmocca approved these changes

2022-06-30 11:05 UTC, carmocca commented on src/pytorch_lightning/loops/epoch/training_epoch_loop.py
> +        state_dict["batches_that_stepped"] = self._batches_that_stepped
I would keep the underscore

```suggestion
        state_dict["_batches_that_stepped"] = self._batches_that_stepped
```

2022-06-30 11:18 UTC, rohitgr7 commented on src/pytorch_lightning/loops/epoch/training_epoch_loop.py
> +        self._batches_that_stepped = state_dict.get("batches_that_stepped")
```suggestion
        self._batches_that_stepped = state_dict.get("_batches_that_stepped")
```

2022-06-30 11:18 UTC, rohitgr7 commented on tests/tests_pytorch/loops/test_loop_state_dict.py
> +            "epoch_loop.state_dict": {"batches_that_stepped": 0},
```suggestion
            "epoch_loop.state_dict": {"_batches_that_stepped": 0},
```

2022-06-30 17:34 UTC, Borda approved these changes

2022-07-01 03:47 UTC, awaelchli requested changes

2022-07-01 03:47 UTC, awaelchli commented on src/pytorch_lightning/loops/epoch/training_epoch_loop.py
> +        self._batches_that_stepped = state_dict.get("_batches_that_stepped")
How is mypy passing this test? _batches_that_stepped here is an int, but get() can return None.

```suggestion
        self._batches_that_stepped = state_dict.get("_batches_that_stepped", 0)
```

2022-07-01 08:08 UTC, awaelchli approved these changes

2022-07-12 09:45 UTC, merged