Clarification on the payload doc string
Lightning-AI/lightning pull request #14990
Opened 2022-10-04 08:29 UTC by krishnakalyan3

## What does this PR do?

Fixes #\<issue_number>

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-10-04 09:39 UTC, alecmerdler approved these changes
Thanks for the clarification!

2022-10-04 15:16 UTC, otaj approved these changes

2022-10-04 15:16 UTC, otaj commented on src/lightning_app/storage/payload.py
> +    Payload is similar to Drive, Payload object is a pickled file that is unpickled into another other work.
```suggestion
    Payload is similar to Drive, Payload object is a pickled file that is unpickled into another work.
```

2022-10-04 23:10 UTC, awaelchli approved these changes

2022-10-05 10:51 UTC, Borda approved these changes

2022-10-07 10:21 UTC, lantiga requested changes

2022-10-07 10:21 UTC, lantiga commented on src/lightning_app/storage/payload.py
> +    :class:`~lightning_app.storage.path.Path`.
```suggestion
    :class:`~lightning_app.storage.payload.Payload`.
```

2022-10-07 10:21 UTC, lantiga commented on src/lightning_app/storage/payload.py
> +    Payload is similar to Drive, Payload object is a pickled file that is unpickled into another work.
```suggestion
    `Payload` is used to hold large objects as part of the app state. In this case the state variable will only hold a reference to the object, while the object itself will be serialized and transferred outside the state. Currently `Payload` serializes using `pickle` and transfers through `s3` (similarly to `Drive`), but `BasePayload` can be subclassed to support different serialization and transfer mechanisms.
```

2022-10-29 10:04 UTC, closed without merging