CI: trigger PL for lite
Lightning-AI/lightning pull request #15402
Opened 2022-10-28 20:57 UTC by Borda

## What does this PR do?

As PL is not dependent on Lite, it makes sense to run testing of PL when ever we make changes in Lite...

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-10-28 21:08 UTC, awaelchli approved these changes

2022-10-30 16:27 UTC, carmocca requested changes
Can you add the new accelerator jobs to checkgroup?

2022-10-30 16:27 UTC, carmocca commented on .github/workflows/ci-pytorch-tests.yml
> +      - "requirements/lite/**"
These are duplicated

2022-10-30 16:27 UTC, carmocca commented on .github/workflows/ci-pytorch-tests-slow.yml
> +      - "requirements/lite/**"
These are duplicated

2022-10-31 11:20 UTC, Borda commented on .github/workflows/ci-pytorch-tests-slow.yml
> +      - "src/lightning_lite/**"
```suggestion
```

2022-10-31 11:20 UTC, Borda commented on .github/workflows/ci-pytorch-tests.yml
> +      - "src/lightning_lite/**"
```suggestion
```

2022-10-31 11:21 UTC, Borda commented on .github/workflows/ci-pytorch-tests.yml
> +      - "requirements/lite/**"
good catch, fixed :)

2022-10-31 11:21 UTC, Borda commented on .github/workflows/ci-pytorch-tests-slow.yml
> +      - "requirements/lite/**"
good catch, fixed :)

2022-10-31 12:33 UTC, Borda commented
> Can you add the new accelerator jobs to checkgroup?

I think it is fine, but if you suggest, I can do it :)

2022-10-31 14:42 UTC, carmocca approved these changes

2022-10-31 14:43 UTC, carmocca commented
Done!

Note that this is a bit overkill because Lite does not support HPUs or IPUs, so there's very little code shared. But it's okay since tests run fast.

2022-10-31 14:48 UTC, merged