Added check in WandbLogger checkpointing to convert Tensor to float for metadata
Lightning-AI/lightning pull request #15625
Opened 2022-11-10 18:19 UTC by manangoel99

## What does this PR do?

This PR fixes a bug in which the score returned to the WandbLogger while checkpointing is a Tensor but the W&B artifact metadata must have a float value.

A check has been added that in case the score is a tensor, it is converted to float.

Fixes #15624 

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-11-10 22:07 UTC, Borda commented on src/pytorch_lightning/loggers/wandb.py
> +                t = t.item()
```suggestion
            if isinstance(p, Tensor):
                p = p.item()
            if isinstance(t, Tensor):
                t = t.item()
```

2022-11-10 22:17 UTC, awaelchli requested changes

2022-11-10 22:17 UTC, awaelchli commented on src/pytorch_lightning/loggers/wandb.py
> +                t = t.item()
These code paths will never be taken. p is a path and t is a timestamp. Could you verify that #15543 fixes the issue for you? Thanks!

2022-11-11 16:28 UTC, manangoel99 commented
Yes! #15544 fixes the issue.
Closing. When is the next release of pytorch lightning expected?

2022-11-11 16:28 UTC, closed without merging

2022-11-11 16:33 UTC, awaelchli commented
Thanks for confirming. It was released yesterday (1.8.1).