Remove implicit frontend testing from `testing.run_app_in_cloud`
Lightning-AI/lightning pull request #16741
Opened 2023-02-13 12:49 UTC by justusschock

## What does this PR do?

This removes implicit frontend testing from run_app_in_cloud (that wasn't valid with recent frontend changes).

Unblocks #16650 

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ x Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @borda

2023-02-14 12:05 UTC, awaelchli approved these changes

2023-02-14 19:41 UTC, ethanwharris approved these changes
Thanks for this!

2023-02-14 20:03 UTC, tchaton requested changes
Just blocking until there is more context. Quite unclear why we remove the auth + admin view.

2023-02-14 20:40 UTC, tchaton approved these changes
LGTM !

2023-02-22 13:48 UTC, ethanwharris commented on tests/integrations_app/flagship/test_flashy.py
> +    with run_app_in_cloud(_PATH_INTEGRATIONS_DIR) as (_, view_page, fetch_logs, _):
```suggestion
    with run_app_in_cloud(_PATH_INTEGRATIONS_DIR) as (admin_page, view_page, fetch_logs, _):
```

2023-02-22 14:48 UTC, merged