Revert "import neptune instead of import neptune.new"
Lightning-AI/lightning pull request #16898
Opened 2023-02-28 11:42 UTC by wouterzwerink

Reverts Lightning-AI/lightning#16888

See https://github.com/Lightning-AI/lightning/pull/16888#issuecomment-1448032165 for further information

2023-02-28 13:57 UTC, awaelchli approved these changes

2023-02-28 15:53 UTC, carmocca requested changes
Let's see if https://github.com/Lightning-AI/lightning/pull/16761 lands before the 2.0 release. Otherwise we'll merge this to avoid introducing the breaking change. Requesting changes to block in the meantime

2023-03-13 14:18 UTC, carmocca commented
Looks like it's not happening. Unblocking

2023-03-13 14:18 UTC, carmocca approved these changes

2023-03-13 14:50 UTC, merged