update links to Discord
Lightning-AI/lightning pull request #17087
Opened 2023-03-14 22:43 UTC by Borda

## What does this PR do?

 switching to discord

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

2023-03-14 22:57 UTC, awaelchli commented
@Borda Discord invite links expire after 7 days. Is this a permanent one? @lantiga created a permanent invite link last week and it looks like this: https://discord.gg/VptPCZkGNa
It is different from the one you have, could you please double check it? [See internal slack message.](https://lightning-ai-corp.slack.com/archives/C03D2J017QV/p1678186062170019?thread_ts=1678183600.838619&cid=C03D2J017QV)

2023-03-15 02:04 UTC, Borda commented
> Discord invite links expire after 7 days. Is this a permanent one? @lantiga created a permanent invite link last week and it looks like this: [discord.gg/VptPCZkGNa](https://discord.gg/VptPCZkGNa)

thank you, fixed :)

2023-03-15 03:13 UTC, awaelchli approved these changes

2023-03-15 06:46 UTC, lantiga requested changes

2023-03-15 06:46 UTC, lantiga commented on .github/BECOMING_A_CORE_CONTRIBUTOR.md
> +We have an active [Discord](https://discord.gg/VptPCZkGNa) and [Slack](https://www.pytorchlightning.ai/community) community, where questions are asked daily.
```suggestion
We have an active [Discord](https://discord.gg/VptPCZkGNa) community, where questions are asked daily.
```

2023-03-15 06:46 UTC, lantiga commented on .github/BECOMING_A_CORE_CONTRIBUTOR.md
> +We have an active [Discord](https://discord.gg/VptPCZkGNa) and [Slack](https://www.pytorchlightning.ai/community) community, where questions are asked daily.
Let's remove Slack. The people that are in Slack today won't check back here anyway

2023-03-15 12:14 UTC, lantiga approved these changes

2023-03-15 12:15 UTC, carmocca approved these changes

2023-03-15 12:17 UTC, carmocca reviewed
CI failure here is real. Do not force merge it yet

2023-03-15 12:17 UTC, carmocca commented on docs/source-app/levels/expert/index.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/get_started/go_beyond_training.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/get_started/jumpstart_from_app_gallery.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/get_started/jumpstart_from_component_gallery.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/get_started/training_with_apps.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/get_started/what_app_can_do.rst
>  ----
```suggestion

```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/levels/advanced/index.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/levels/basic/build_a_lightning_component.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/levels/basic/index.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/levels/expert/index.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-app/levels/intermediate/index.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/common_usecases.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/expertise_levels.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/levels/advanced.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/levels/core_skills.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/levels/expert.rst
>  ----
```suggestion
```

2023-03-15 12:19 UTC, awaelchli commented on docs/source-pytorch/levels/intermediate.rst
>  ----
```suggestion
```

2023-03-15 12:33 UTC, merged