Simplify CI by removing unused Docker images
Lightning-AI/lightning pull request #17348
Opened 2023-04-12 13:44 UTC by carmocca

## What does this PR do?

See title.

These images are not unused by the project.
This PR proposes that CI is trimmed down with the intent of simplifying it.

cc @carmocca @borda

2023-04-12 13:45 UTC, carmocca commented on .github/checkgroup.yml
>        - "build-NGC"
@Borda Is the NGC image still used anywhere? Could we drop it too?

2023-04-13 17:30 UTC, awaelchli approved these changes

2023-04-13 22:40 UTC, Borda requested changes
We shall keep the production PL images, fixed in #17353

2023-04-13 23:14 UTC, carmocca commented
Closing since Jirka doesn't agree with this

2023-04-13 23:14 UTC, closed without merging

2023-04-14 05:03 UTC, Borda commented
> Closing since Jirka doesn't agree with this



> Closing since Jirka doesn't agree with this

If the issue is with the number of image, I am fine to prune them, but let's keep at least one per release