Compose RunIf utilities
Lightning-AI/lightning pull request #17520
Opened 2023-04-28 16:20 UTC by carmocca

## What does this PR do?

See title

2023-04-28 17:00 UTC, Borda requested changes

2023-04-28 17:41 UTC, carmocca commented on src/lightning/pytorch/utilities/testing/_runif.py
> -    min_cuda_gpus: int = 0,
Sorry, what do you mean?

2023-04-28 20:52 UTC, Borda commented on src/lightning/pytorch/utilities/testing/_runif.py
> -    min_cuda_gpus: int = 0,
It is not clear to a user that he can use these arguments as they are given in other functions for IDE hints that are silent... in such cases can utilize both `RunIf`

```py
@BaseRunIf(min_torch='1.12', ...)  # <- Fabric version
@ExtendRunIf(psutil=True, ...)  # <- Pytorch version
def test_anytning_you_want(...)

```

2023-05-02 22:34 UTC, Borda commented on src/lightning/fabric/utilities/testing/_runif.py
> -    **kwargs: Any,
why no kwasrgs?

2023-05-02 22:35 UTC, Borda commented on src/lightning/pytorch/utilities/testing/_runif.py
> +    reasons, kwargs = FabricRunIf(**kwargs)
here IDE hint wot help with suggesting the base args

2023-05-02 22:35 UTC, Borda commented on src/lightning/pytorch/utilities/testing/_runif.py
> -    kwargs.pop("reason", None)
this should stay

2023-05-03 02:01 UTC, carmocca commented on src/lightning/fabric/utilities/testing/_runif.py
> -    **kwargs: Any,
It's unused now

2023-05-03 02:01 UTC, carmocca commented on src/lightning/pytorch/utilities/testing/_runif.py
> -    min_cuda_gpus: int = 0,
Added back

2023-05-03 02:01 UTC, carmocca commented on src/lightning/pytorch/utilities/testing/_runif.py
> -    kwargs.pop("reason", None)
There's no kwargs anymore

2023-05-04 21:21 UTC, awaelchli approved these changes
I'm suspicious of the fact that this runif gets refactored so often. Now there are four different RunIf. The previous version was definitely easy to understand and adapt for other projects.

2023-05-04 22:10 UTC, Borda commented
> I'm suspicious of the fact that this runif gets refactored so often. Now there are four different RunIf. The previous version was definitely easy to understand and adapt for other projects.

I did not change much (I believe) on the internals, mostly moved it to the package to be re-used...

2023-05-04 23:21 UTC, merged